### ISSUE TITLE
Using ng-html2js with html2js

### ISSUE THREAD

**Issue by senorpasajero** [karma-runner/karma-ng-html2js-preprocessor#65] opened 2015-03-17 22:09 UTC
Hi Guys, I would like to use ng-html2js with html2js but I have this error when I install ng-html2js.

'undefined' is not an object (evaluating 'window.__html__['PATH.json']').

Some ideas about it?

**Comment by omichelsen** [comment] 2015-04-22 13:14
The problem is [this line](https://github.com/karma-runner/karma-ng-html2js-preprocessor/blob/master/lib/index.js#L5). It seems it should have been removed in v0.1.1 but it has not happened yet as of v0.1.2.

Essentially this plugin registers itself twice and overrides html2js if it is loaded.

**Comment by Dignifiedquire** [comment] 2015-07-08 21:42
Closing in favor of #43

**Closed by Dignifiedquire** 2015-07-08 21:42 UTC
